// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protother.proto

package protother

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ChartType int32

const (
	ChartType_LINE_CHART ChartType = 0
	ChartType_PIE_CHART  ChartType = 1
	ChartType_BAR_CHART  ChartType = 2
)

var ChartType_name = map[int32]string{
	0: "LINE_CHART",
	1: "PIE_CHART",
	2: "BAR_CHART",
}

var ChartType_value = map[string]int32{
	"LINE_CHART": 0,
	"PIE_CHART":  1,
	"BAR_CHART":  2,
}

func (x ChartType) String() string {
	return proto.EnumName(ChartType_name, int32(x))
}

func (ChartType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_17452f9afc4e24c8, []int{0}
}

type PingRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17452f9afc4e24c8, []int{0}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PingReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReply) Reset()         { *m = PingReply{} }
func (m *PingReply) String() string { return proto.CompactTextString(m) }
func (*PingReply) ProtoMessage()    {}
func (*PingReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_17452f9afc4e24c8, []int{1}
}

func (m *PingReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReply.Unmarshal(m, b)
}
func (m *PingReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReply.Marshal(b, m, deterministic)
}
func (m *PingReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReply.Merge(m, src)
}
func (m *PingReply) XXX_Size() int {
	return xxx_messageInfo_PingReply.Size(m)
}
func (m *PingReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReply.DiscardUnknown(m)
}

var xxx_messageInfo_PingReply proto.InternalMessageInfo

func (m *PingReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type TaskRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskRequest) Reset()         { *m = TaskRequest{} }
func (m *TaskRequest) String() string { return proto.CompactTextString(m) }
func (*TaskRequest) ProtoMessage()    {}
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17452f9afc4e24c8, []int{2}
}

func (m *TaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskRequest.Unmarshal(m, b)
}
func (m *TaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskRequest.Marshal(b, m, deterministic)
}
func (m *TaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskRequest.Merge(m, src)
}
func (m *TaskRequest) XXX_Size() int {
	return xxx_messageInfo_TaskRequest.Size(m)
}
func (m *TaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskRequest proto.InternalMessageInfo

func (m *TaskRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UTask struct {
	TaskMane             string   `protobuf:"bytes,1,opt,name=TaskMane,proto3" json:"TaskMane,omitempty"`
	Project              string   `protobuf:"bytes,2,opt,name=Project,proto3" json:"Project,omitempty"`
	Date                 string   `protobuf:"bytes,3,opt,name=Date,proto3" json:"Date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UTask) Reset()         { *m = UTask{} }
func (m *UTask) String() string { return proto.CompactTextString(m) }
func (*UTask) ProtoMessage()    {}
func (*UTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_17452f9afc4e24c8, []int{3}
}

func (m *UTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UTask.Unmarshal(m, b)
}
func (m *UTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UTask.Marshal(b, m, deterministic)
}
func (m *UTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UTask.Merge(m, src)
}
func (m *UTask) XXX_Size() int {
	return xxx_messageInfo_UTask.Size(m)
}
func (m *UTask) XXX_DiscardUnknown() {
	xxx_messageInfo_UTask.DiscardUnknown(m)
}

var xxx_messageInfo_UTask proto.InternalMessageInfo

func (m *UTask) GetTaskMane() string {
	if m != nil {
		return m.TaskMane
	}
	return ""
}

func (m *UTask) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *UTask) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

type DailyTaskCount struct {
	Date                 string    `protobuf:"bytes,1,opt,name=Date,proto3" json:"Date,omitempty"`
	Count                int32     `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	ChartType            ChartType `protobuf:"varint,3,opt,name=chartType,proto3,enum=protother.ChartType" json:"chartType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DailyTaskCount) Reset()         { *m = DailyTaskCount{} }
func (m *DailyTaskCount) String() string { return proto.CompactTextString(m) }
func (*DailyTaskCount) ProtoMessage()    {}
func (*DailyTaskCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_17452f9afc4e24c8, []int{4}
}

func (m *DailyTaskCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DailyTaskCount.Unmarshal(m, b)
}
func (m *DailyTaskCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DailyTaskCount.Marshal(b, m, deterministic)
}
func (m *DailyTaskCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DailyTaskCount.Merge(m, src)
}
func (m *DailyTaskCount) XXX_Size() int {
	return xxx_messageInfo_DailyTaskCount.Size(m)
}
func (m *DailyTaskCount) XXX_DiscardUnknown() {
	xxx_messageInfo_DailyTaskCount.DiscardUnknown(m)
}

var xxx_messageInfo_DailyTaskCount proto.InternalMessageInfo

func (m *DailyTaskCount) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *DailyTaskCount) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *DailyTaskCount) GetChartType() ChartType {
	if m != nil {
		return m.ChartType
	}
	return ChartType_LINE_CHART
}

type ProjectTaskCount struct {
	Project              string    `protobuf:"bytes,1,opt,name=Project,proto3" json:"Project,omitempty"`
	Count                int32     `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	ChartType            ChartType `protobuf:"varint,3,opt,name=chartType,proto3,enum=protother.ChartType" json:"chartType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ProjectTaskCount) Reset()         { *m = ProjectTaskCount{} }
func (m *ProjectTaskCount) String() string { return proto.CompactTextString(m) }
func (*ProjectTaskCount) ProtoMessage()    {}
func (*ProjectTaskCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_17452f9afc4e24c8, []int{5}
}

func (m *ProjectTaskCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectTaskCount.Unmarshal(m, b)
}
func (m *ProjectTaskCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectTaskCount.Marshal(b, m, deterministic)
}
func (m *ProjectTaskCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectTaskCount.Merge(m, src)
}
func (m *ProjectTaskCount) XXX_Size() int {
	return xxx_messageInfo_ProjectTaskCount.Size(m)
}
func (m *ProjectTaskCount) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectTaskCount.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectTaskCount proto.InternalMessageInfo

func (m *ProjectTaskCount) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *ProjectTaskCount) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ProjectTaskCount) GetChartType() ChartType {
	if m != nil {
		return m.ChartType
	}
	return ChartType_LINE_CHART
}

type PlotRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlotRequest) Reset()         { *m = PlotRequest{} }
func (m *PlotRequest) String() string { return proto.CompactTextString(m) }
func (*PlotRequest) ProtoMessage()    {}
func (*PlotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17452f9afc4e24c8, []int{6}
}

func (m *PlotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlotRequest.Unmarshal(m, b)
}
func (m *PlotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlotRequest.Marshal(b, m, deterministic)
}
func (m *PlotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlotRequest.Merge(m, src)
}
func (m *PlotRequest) XXX_Size() int {
	return xxx_messageInfo_PlotRequest.Size(m)
}
func (m *PlotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlotRequest proto.InternalMessageInfo

func (m *PlotRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PointReply struct {
	X                    string    `protobuf:"bytes,1,opt,name=X,proto3" json:"X,omitempty"`
	Y                    int32     `protobuf:"varint,2,opt,name=Y,proto3" json:"Y,omitempty"`
	EChartType           ChartType `protobuf:"varint,3,opt,name=EChartType,proto3,enum=protother.ChartType" json:"EChartType,omitempty"`
	XLabel               string    `protobuf:"bytes,4,opt,name=XLabel,proto3" json:"XLabel,omitempty"`
	YLabel               string    `protobuf:"bytes,5,opt,name=YLabel,proto3" json:"YLabel,omitempty"`
	Title                string    `protobuf:"bytes,6,opt,name=Title,proto3" json:"Title,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PointReply) Reset()         { *m = PointReply{} }
func (m *PointReply) String() string { return proto.CompactTextString(m) }
func (*PointReply) ProtoMessage()    {}
func (*PointReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_17452f9afc4e24c8, []int{7}
}

func (m *PointReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PointReply.Unmarshal(m, b)
}
func (m *PointReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PointReply.Marshal(b, m, deterministic)
}
func (m *PointReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PointReply.Merge(m, src)
}
func (m *PointReply) XXX_Size() int {
	return xxx_messageInfo_PointReply.Size(m)
}
func (m *PointReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PointReply.DiscardUnknown(m)
}

var xxx_messageInfo_PointReply proto.InternalMessageInfo

func (m *PointReply) GetX() string {
	if m != nil {
		return m.X
	}
	return ""
}

func (m *PointReply) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *PointReply) GetEChartType() ChartType {
	if m != nil {
		return m.EChartType
	}
	return ChartType_LINE_CHART
}

func (m *PointReply) GetXLabel() string {
	if m != nil {
		return m.XLabel
	}
	return ""
}

func (m *PointReply) GetYLabel() string {
	if m != nil {
		return m.YLabel
	}
	return ""
}

func (m *PointReply) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func init() {
	proto.RegisterEnum("protother.ChartType", ChartType_name, ChartType_value)
	proto.RegisterType((*PingRequest)(nil), "protother.PingRequest")
	proto.RegisterType((*PingReply)(nil), "protother.PingReply")
	proto.RegisterType((*TaskRequest)(nil), "protother.TaskRequest")
	proto.RegisterType((*UTask)(nil), "protother.UTask")
	proto.RegisterType((*DailyTaskCount)(nil), "protother.DailyTaskCount")
	proto.RegisterType((*ProjectTaskCount)(nil), "protother.ProjectTaskCount")
	proto.RegisterType((*PlotRequest)(nil), "protother.PlotRequest")
	proto.RegisterType((*PointReply)(nil), "protother.PointReply")
}

func init() {
	proto.RegisterFile("protother.proto", fileDescriptor_17452f9afc4e24c8)
}

var fileDescriptor_17452f9afc4e24c8 = []byte{
	// 434 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xd1, 0x8a, 0xda, 0x40,
	0x14, 0x75, 0xac, 0x51, 0x73, 0x6d, 0xad, 0x9d, 0x5a, 0x49, 0xd3, 0x97, 0x12, 0x28, 0x96, 0x3e,
	0x48, 0xb1, 0xa5, 0xb4, 0xd0, 0x17, 0x1b, 0xc5, 0x5a, 0x54, 0xd2, 0x90, 0x05, 0x7d, 0x5a, 0xa2,
	0x0c, 0x9a, 0xdd, 0x90, 0xb8, 0xc9, 0xb8, 0xe0, 0xff, 0xec, 0x1f, 0xed, 0x0f, 0x2d, 0x33, 0x93,
	0x98, 0x89, 0xe2, 0xba, 0x0f, 0xfb, 0x94, 0x39, 0x27, 0xe7, 0x9c, 0xb9, 0xdc, 0x7b, 0x07, 0x5e,
	0x6f, 0xa2, 0x90, 0x86, 0x74, 0x4d, 0xa2, 0x0e, 0x3f, 0x61, 0x75, 0x4f, 0x18, 0x6d, 0xa8, 0x59,
	0x5e, 0xb0, 0xb2, 0xc9, 0xcd, 0x96, 0xc4, 0x14, 0x6b, 0x50, 0x99, 0x90, 0x38, 0x76, 0x57, 0x44,
	0x43, 0x1f, 0xd1, 0x67, 0xd5, 0x4e, 0xa1, 0xf1, 0x09, 0x54, 0x21, 0xdc, 0xf8, 0xbb, 0x47, 0x64,
	0x6d, 0xa8, 0x39, 0x6e, 0x7c, 0x7d, 0x3e, 0xef, 0x3f, 0x28, 0x17, 0x4c, 0x89, 0x75, 0xa8, 0xb2,
	0xef, 0xc4, 0x0d, 0x52, 0xcd, 0x1e, 0x33, 0xbb, 0x15, 0x85, 0x57, 0x64, 0x49, 0xb5, 0xa2, 0xb0,
	0x27, 0x10, 0x63, 0x28, 0xf5, 0x5d, 0x4a, 0xb4, 0x17, 0x9c, 0xe6, 0x67, 0x23, 0x80, 0x7a, 0xdf,
	0xf5, 0xfc, 0x1d, 0xb3, 0x9b, 0xe1, 0x36, 0xc8, 0x54, 0x28, 0x53, 0xe1, 0x26, 0x28, 0xfc, 0x27,
	0x4f, 0x54, 0x6c, 0x01, 0x70, 0x17, 0xd4, 0xe5, 0xda, 0x8d, 0xa8, 0xb3, 0xdb, 0x88, 0xd0, 0x7a,
	0xb7, 0xd9, 0xc9, 0xfa, 0x66, 0xa6, 0xff, 0xec, 0x4c, 0x66, 0xdc, 0x42, 0x23, 0x29, 0x27, 0xbb,
	0x51, 0xaa, 0x18, 0xe5, 0x2b, 0x7e, 0xbe, 0x7b, 0xd9, 0xcc, 0xfc, 0x90, 0x9e, 0xef, 0xf1, 0x1d,
	0x02, 0xb0, 0x42, 0x2f, 0xa0, 0x62, 0x6a, 0x2f, 0x01, 0xcd, 0x12, 0x09, 0x9a, 0x31, 0x34, 0x4f,
	0x6a, 0x41, 0x73, 0xfc, 0x1d, 0x60, 0x60, 0x3e, 0xa9, 0x10, 0x49, 0x87, 0x5b, 0x50, 0x9e, 0x8d,
	0xdd, 0x05, 0xf1, 0xb5, 0x12, 0x8f, 0x4d, 0x10, 0xe3, 0xe7, 0x82, 0x57, 0x04, 0x2f, 0x10, 0xeb,
	0x81, 0xe3, 0x51, 0x9f, 0x68, 0x65, 0x4e, 0x0b, 0xf0, 0xe5, 0x17, 0xa8, 0x59, 0x64, 0x1d, 0x60,
	0x3c, 0x9a, 0x0e, 0x2e, 0xcd, 0xbf, 0x3d, 0xdb, 0x69, 0x14, 0xf0, 0x2b, 0x50, 0xad, 0x51, 0x0a,
	0x11, 0x83, 0x7f, 0x7a, 0x76, 0x02, 0x8b, 0xdd, 0xfb, 0x22, 0x28, 0xac, 0xf9, 0x31, 0xfe, 0x09,
	0xd5, 0x21, 0xa1, 0xe2, 0xdc, 0x92, 0x0a, 0x97, 0xb6, 0x51, 0x6f, 0x48, 0x3c, 0x5f, 0x3e, 0xa3,
	0xf0, 0x15, 0xe1, 0x7f, 0xf0, 0x66, 0x48, 0xe8, 0xc1, 0xe6, 0x9c, 0x8a, 0x78, 0x2f, 0xf1, 0x79,
	0x0b, 0xcf, 0x9a, 0xc2, 0xdb, 0x21, 0xa1, 0x47, 0x5b, 0x71, 0x2a, 0xed, 0x83, 0xc4, 0x1f, 0x9a,
	0x78, 0xde, 0x6f, 0xa8, 0xb0, 0x3c, 0x3f, 0xcc, 0x67, 0x48, 0xe3, 0xd7, 0xdf, 0xc9, 0xfc, 0x7e,
	0xd8, 0xdc, 0xfd, 0x03, 0x4a, 0xec, 0xcd, 0xe6, 0xad, 0xd9, 0x6b, 0xd7, 0x9b, 0x47, 0x3c, 0x77,
	0x2e, 0xca, 0x9c, 0xfe, 0xf6, 0x10, 0x00, 0x00, 0xff, 0xff, 0xf7, 0xb2, 0x9f, 0x1b, 0x39, 0x04,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TasksClient is the client API for Tasks service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TasksClient interface {
	GetTasks(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (Tasks_GetTasksClient, error)
	GetDailyTaskCount(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (Tasks_GetDailyTaskCountClient, error)
	GetProjectTaskCount(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (Tasks_GetProjectTaskCountClient, error)
	GetPlot(ctx context.Context, in *PlotRequest, opts ...grpc.CallOption) (Tasks_GetPlotClient, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
}

type tasksClient struct {
	cc grpc.ClientConnInterface
}

func NewTasksClient(cc grpc.ClientConnInterface) TasksClient {
	return &tasksClient{cc}
}

func (c *tasksClient) GetTasks(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (Tasks_GetTasksClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Tasks_serviceDesc.Streams[0], "/protother.Tasks/GetTasks", opts...)
	if err != nil {
		return nil, err
	}
	x := &tasksGetTasksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Tasks_GetTasksClient interface {
	Recv() (*UTask, error)
	grpc.ClientStream
}

type tasksGetTasksClient struct {
	grpc.ClientStream
}

func (x *tasksGetTasksClient) Recv() (*UTask, error) {
	m := new(UTask)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tasksClient) GetDailyTaskCount(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (Tasks_GetDailyTaskCountClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Tasks_serviceDesc.Streams[1], "/protother.Tasks/GetDailyTaskCount", opts...)
	if err != nil {
		return nil, err
	}
	x := &tasksGetDailyTaskCountClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Tasks_GetDailyTaskCountClient interface {
	Recv() (*DailyTaskCount, error)
	grpc.ClientStream
}

type tasksGetDailyTaskCountClient struct {
	grpc.ClientStream
}

func (x *tasksGetDailyTaskCountClient) Recv() (*DailyTaskCount, error) {
	m := new(DailyTaskCount)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tasksClient) GetProjectTaskCount(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (Tasks_GetProjectTaskCountClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Tasks_serviceDesc.Streams[2], "/protother.Tasks/GetProjectTaskCount", opts...)
	if err != nil {
		return nil, err
	}
	x := &tasksGetProjectTaskCountClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Tasks_GetProjectTaskCountClient interface {
	Recv() (*ProjectTaskCount, error)
	grpc.ClientStream
}

type tasksGetProjectTaskCountClient struct {
	grpc.ClientStream
}

func (x *tasksGetProjectTaskCountClient) Recv() (*ProjectTaskCount, error) {
	m := new(ProjectTaskCount)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tasksClient) GetPlot(ctx context.Context, in *PlotRequest, opts ...grpc.CallOption) (Tasks_GetPlotClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Tasks_serviceDesc.Streams[3], "/protother.Tasks/GetPlot", opts...)
	if err != nil {
		return nil, err
	}
	x := &tasksGetPlotClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Tasks_GetPlotClient interface {
	Recv() (*PointReply, error)
	grpc.ClientStream
}

type tasksGetPlotClient struct {
	grpc.ClientStream
}

func (x *tasksGetPlotClient) Recv() (*PointReply, error) {
	m := new(PointReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tasksClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := c.cc.Invoke(ctx, "/protother.Tasks/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TasksServer is the server API for Tasks service.
type TasksServer interface {
	GetTasks(*TaskRequest, Tasks_GetTasksServer) error
	GetDailyTaskCount(*TaskRequest, Tasks_GetDailyTaskCountServer) error
	GetProjectTaskCount(*TaskRequest, Tasks_GetProjectTaskCountServer) error
	GetPlot(*PlotRequest, Tasks_GetPlotServer) error
	Ping(context.Context, *PingRequest) (*PingReply, error)
}

// UnimplementedTasksServer can be embedded to have forward compatible implementations.
type UnimplementedTasksServer struct {
}

func (*UnimplementedTasksServer) GetTasks(req *TaskRequest, srv Tasks_GetTasksServer) error {
	return status.Errorf(codes.Unimplemented, "method GetTasks not implemented")
}
func (*UnimplementedTasksServer) GetDailyTaskCount(req *TaskRequest, srv Tasks_GetDailyTaskCountServer) error {
	return status.Errorf(codes.Unimplemented, "method GetDailyTaskCount not implemented")
}
func (*UnimplementedTasksServer) GetProjectTaskCount(req *TaskRequest, srv Tasks_GetProjectTaskCountServer) error {
	return status.Errorf(codes.Unimplemented, "method GetProjectTaskCount not implemented")
}
func (*UnimplementedTasksServer) GetPlot(req *PlotRequest, srv Tasks_GetPlotServer) error {
	return status.Errorf(codes.Unimplemented, "method GetPlot not implemented")
}
func (*UnimplementedTasksServer) Ping(ctx context.Context, req *PingRequest) (*PingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}

func RegisterTasksServer(s *grpc.Server, srv TasksServer) {
	s.RegisterService(&_Tasks_serviceDesc, srv)
}

func _Tasks_GetTasks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TaskRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TasksServer).GetTasks(m, &tasksGetTasksServer{stream})
}

type Tasks_GetTasksServer interface {
	Send(*UTask) error
	grpc.ServerStream
}

type tasksGetTasksServer struct {
	grpc.ServerStream
}

func (x *tasksGetTasksServer) Send(m *UTask) error {
	return x.ServerStream.SendMsg(m)
}

func _Tasks_GetDailyTaskCount_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TaskRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TasksServer).GetDailyTaskCount(m, &tasksGetDailyTaskCountServer{stream})
}

type Tasks_GetDailyTaskCountServer interface {
	Send(*DailyTaskCount) error
	grpc.ServerStream
}

type tasksGetDailyTaskCountServer struct {
	grpc.ServerStream
}

func (x *tasksGetDailyTaskCountServer) Send(m *DailyTaskCount) error {
	return x.ServerStream.SendMsg(m)
}

func _Tasks_GetProjectTaskCount_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TaskRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TasksServer).GetProjectTaskCount(m, &tasksGetProjectTaskCountServer{stream})
}

type Tasks_GetProjectTaskCountServer interface {
	Send(*ProjectTaskCount) error
	grpc.ServerStream
}

type tasksGetProjectTaskCountServer struct {
	grpc.ServerStream
}

func (x *tasksGetProjectTaskCountServer) Send(m *ProjectTaskCount) error {
	return x.ServerStream.SendMsg(m)
}

func _Tasks_GetPlot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PlotRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TasksServer).GetPlot(m, &tasksGetPlotServer{stream})
}

type Tasks_GetPlotServer interface {
	Send(*PointReply) error
	grpc.ServerStream
}

type tasksGetPlotServer struct {
	grpc.ServerStream
}

func (x *tasksGetPlotServer) Send(m *PointReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Tasks_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protother.Tasks/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tasks_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protother.Tasks",
	HandlerType: (*TasksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Tasks_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetTasks",
			Handler:       _Tasks_GetTasks_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetDailyTaskCount",
			Handler:       _Tasks_GetDailyTaskCount_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetProjectTaskCount",
			Handler:       _Tasks_GetProjectTaskCount_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetPlot",
			Handler:       _Tasks_GetPlot_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protother.proto",
}
