# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protother.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protother.proto',
  package='protother',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0fprotother.proto\x12\tprotother\"\x1e\n\x0bPingRequest\x12\x0f\n\x07Message\x18\x01 \x01(\t\"\x1c\n\tPingReply\x12\x0f\n\x07Message\x18\x01 \x01(\t\"\x1e\n\x0bTaskRequest\x12\x0f\n\x07Message\x18\x01 \x01(\t\"8\n\x05UTask\x12\x10\n\x08TaskMane\x18\x01 \x01(\t\x12\x0f\n\x07Project\x18\x02 \x01(\t\x12\x0c\n\x04\x44\x61te\x18\x03 \x01(\t\"V\n\x0e\x44\x61ilyTaskCount\x12\x0c\n\x04\x44\x61te\x18\x01 \x01(\t\x12\r\n\x05\x43ount\x18\x02 \x01(\x05\x12\'\n\tchartType\x18\x03 \x01(\x0e\x32\x14.protother.ChartType\"[\n\x10ProjectTaskCount\x12\x0f\n\x07Project\x18\x01 \x01(\t\x12\r\n\x05\x43ount\x18\x02 \x01(\x05\x12\'\n\tchartType\x18\x03 \x01(\x0e\x32\x14.protother.ChartType\"\x1e\n\x0bPlotRequest\x12\x0f\n\x07Message\x18\x01 \x01(\t\"\x8e\x01\n\nPointReply\x12\t\n\x01X\x18\x01 \x01(\t\x12\t\n\x01Y\x18\x02 \x01(\x05\x12(\n\nEChartType\x18\x03 \x01(\x0e\x32\x14.protother.ChartType\x12\x0e\n\x06XLabel\x18\x04 \x01(\t\x12\x0e\n\x06YLabel\x18\x05 \x01(\t\x12\r\n\x05Title\x18\x06 \x01(\t\x12\x11\n\tColorCode\x18\x07 \x01(\t*9\n\tChartType\x12\x0e\n\nLINE_CHART\x10\x00\x12\r\n\tPIE_CHART\x10\x01\x12\r\n\tBAR_CHART\x10\x02\x32\xd3\x02\n\x05Tasks\x12\x38\n\x08GetTasks\x12\x16.protother.TaskRequest\x1a\x10.protother.UTask\"\x00\x30\x01\x12J\n\x11GetDailyTaskCount\x12\x16.protother.TaskRequest\x1a\x19.protother.DailyTaskCount\"\x00\x30\x01\x12N\n\x13GetProjectTaskCount\x12\x16.protother.TaskRequest\x1a\x1b.protother.ProjectTaskCount\"\x00\x30\x01\x12<\n\x07GetPlot\x12\x16.protother.PlotRequest\x1a\x15.protother.PointReply\"\x00\x30\x01\x12\x36\n\x04Ping\x12\x16.protother.PingRequest\x1a\x14.protother.PingReply\"\x00\x62\x06proto3'
)

_CHARTTYPE = _descriptor.EnumDescriptor(
  name='ChartType',
  full_name='protother.ChartType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LINE_CHART', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PIE_CHART', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BAR_CHART', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=540,
  serialized_end=597,
)
_sym_db.RegisterEnumDescriptor(_CHARTTYPE)

ChartType = enum_type_wrapper.EnumTypeWrapper(_CHARTTYPE)
LINE_CHART = 0
PIE_CHART = 1
BAR_CHART = 2



_PINGREQUEST = _descriptor.Descriptor(
  name='PingRequest',
  full_name='protother.PingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Message', full_name='protother.PingRequest.Message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=60,
)


_PINGREPLY = _descriptor.Descriptor(
  name='PingReply',
  full_name='protother.PingReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Message', full_name='protother.PingReply.Message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=90,
)


_TASKREQUEST = _descriptor.Descriptor(
  name='TaskRequest',
  full_name='protother.TaskRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Message', full_name='protother.TaskRequest.Message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=122,
)


_UTASK = _descriptor.Descriptor(
  name='UTask',
  full_name='protother.UTask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='TaskMane', full_name='protother.UTask.TaskMane', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Project', full_name='protother.UTask.Project', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Date', full_name='protother.UTask.Date', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=180,
)


_DAILYTASKCOUNT = _descriptor.Descriptor(
  name='DailyTaskCount',
  full_name='protother.DailyTaskCount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Date', full_name='protother.DailyTaskCount.Date', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Count', full_name='protother.DailyTaskCount.Count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chartType', full_name='protother.DailyTaskCount.chartType', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=268,
)


_PROJECTTASKCOUNT = _descriptor.Descriptor(
  name='ProjectTaskCount',
  full_name='protother.ProjectTaskCount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Project', full_name='protother.ProjectTaskCount.Project', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Count', full_name='protother.ProjectTaskCount.Count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chartType', full_name='protother.ProjectTaskCount.chartType', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=361,
)


_PLOTREQUEST = _descriptor.Descriptor(
  name='PlotRequest',
  full_name='protother.PlotRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Message', full_name='protother.PlotRequest.Message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=363,
  serialized_end=393,
)


_POINTREPLY = _descriptor.Descriptor(
  name='PointReply',
  full_name='protother.PointReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='X', full_name='protother.PointReply.X', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Y', full_name='protother.PointReply.Y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='EChartType', full_name='protother.PointReply.EChartType', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='XLabel', full_name='protother.PointReply.XLabel', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='YLabel', full_name='protother.PointReply.YLabel', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Title', full_name='protother.PointReply.Title', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ColorCode', full_name='protother.PointReply.ColorCode', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=396,
  serialized_end=538,
)

_DAILYTASKCOUNT.fields_by_name['chartType'].enum_type = _CHARTTYPE
_PROJECTTASKCOUNT.fields_by_name['chartType'].enum_type = _CHARTTYPE
_POINTREPLY.fields_by_name['EChartType'].enum_type = _CHARTTYPE
DESCRIPTOR.message_types_by_name['PingRequest'] = _PINGREQUEST
DESCRIPTOR.message_types_by_name['PingReply'] = _PINGREPLY
DESCRIPTOR.message_types_by_name['TaskRequest'] = _TASKREQUEST
DESCRIPTOR.message_types_by_name['UTask'] = _UTASK
DESCRIPTOR.message_types_by_name['DailyTaskCount'] = _DAILYTASKCOUNT
DESCRIPTOR.message_types_by_name['ProjectTaskCount'] = _PROJECTTASKCOUNT
DESCRIPTOR.message_types_by_name['PlotRequest'] = _PLOTREQUEST
DESCRIPTOR.message_types_by_name['PointReply'] = _POINTREPLY
DESCRIPTOR.enum_types_by_name['ChartType'] = _CHARTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PingRequest = _reflection.GeneratedProtocolMessageType('PingRequest', (_message.Message,), {
  'DESCRIPTOR' : _PINGREQUEST,
  '__module__' : 'protother_pb2'
  # @@protoc_insertion_point(class_scope:protother.PingRequest)
  })
_sym_db.RegisterMessage(PingRequest)

PingReply = _reflection.GeneratedProtocolMessageType('PingReply', (_message.Message,), {
  'DESCRIPTOR' : _PINGREPLY,
  '__module__' : 'protother_pb2'
  # @@protoc_insertion_point(class_scope:protother.PingReply)
  })
_sym_db.RegisterMessage(PingReply)

TaskRequest = _reflection.GeneratedProtocolMessageType('TaskRequest', (_message.Message,), {
  'DESCRIPTOR' : _TASKREQUEST,
  '__module__' : 'protother_pb2'
  # @@protoc_insertion_point(class_scope:protother.TaskRequest)
  })
_sym_db.RegisterMessage(TaskRequest)

UTask = _reflection.GeneratedProtocolMessageType('UTask', (_message.Message,), {
  'DESCRIPTOR' : _UTASK,
  '__module__' : 'protother_pb2'
  # @@protoc_insertion_point(class_scope:protother.UTask)
  })
_sym_db.RegisterMessage(UTask)

DailyTaskCount = _reflection.GeneratedProtocolMessageType('DailyTaskCount', (_message.Message,), {
  'DESCRIPTOR' : _DAILYTASKCOUNT,
  '__module__' : 'protother_pb2'
  # @@protoc_insertion_point(class_scope:protother.DailyTaskCount)
  })
_sym_db.RegisterMessage(DailyTaskCount)

ProjectTaskCount = _reflection.GeneratedProtocolMessageType('ProjectTaskCount', (_message.Message,), {
  'DESCRIPTOR' : _PROJECTTASKCOUNT,
  '__module__' : 'protother_pb2'
  # @@protoc_insertion_point(class_scope:protother.ProjectTaskCount)
  })
_sym_db.RegisterMessage(ProjectTaskCount)

PlotRequest = _reflection.GeneratedProtocolMessageType('PlotRequest', (_message.Message,), {
  'DESCRIPTOR' : _PLOTREQUEST,
  '__module__' : 'protother_pb2'
  # @@protoc_insertion_point(class_scope:protother.PlotRequest)
  })
_sym_db.RegisterMessage(PlotRequest)

PointReply = _reflection.GeneratedProtocolMessageType('PointReply', (_message.Message,), {
  'DESCRIPTOR' : _POINTREPLY,
  '__module__' : 'protother_pb2'
  # @@protoc_insertion_point(class_scope:protother.PointReply)
  })
_sym_db.RegisterMessage(PointReply)



_TASKS = _descriptor.ServiceDescriptor(
  name='Tasks',
  full_name='protother.Tasks',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=600,
  serialized_end=939,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetTasks',
    full_name='protother.Tasks.GetTasks',
    index=0,
    containing_service=None,
    input_type=_TASKREQUEST,
    output_type=_UTASK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetDailyTaskCount',
    full_name='protother.Tasks.GetDailyTaskCount',
    index=1,
    containing_service=None,
    input_type=_TASKREQUEST,
    output_type=_DAILYTASKCOUNT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetProjectTaskCount',
    full_name='protother.Tasks.GetProjectTaskCount',
    index=2,
    containing_service=None,
    input_type=_TASKREQUEST,
    output_type=_PROJECTTASKCOUNT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetPlot',
    full_name='protother.Tasks.GetPlot',
    index=3,
    containing_service=None,
    input_type=_PLOTREQUEST,
    output_type=_POINTREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='protother.Tasks.Ping',
    index=4,
    containing_service=None,
    input_type=_PINGREQUEST,
    output_type=_PINGREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TASKS)

DESCRIPTOR.services_by_name['Tasks'] = _TASKS

# @@protoc_insertion_point(module_scope)
